Update esi sdk
CCI-MOC/esisdk pull request #2
Opened 2024-04-24 00:16 UTC by DanNiESh

Related issue: https://github.com/CCI-MOC/esi/issues/536

2024-04-24 13:51 UTC, tzumainn commented
Looks good! Can you update the description of the PR to be a bit more specific about the contents - e.g., "updates to object attributes, addition of functional tests"?

2024-04-24 14:58 UTC, DanNiESh commented
> Looks good! Can you update the description of the PR to be a bit more specific about the contents - e.g., "updates to object attributes, addition of functional tests"?

Done! I'm now working on python-esileapclient PR. I might update this PR slightly (attribute naming, etc.) to sync with python-esileapclient if necessary. I 'll let you know when this one is in final stage to review.

2024-04-24 15:01 UTC, tzumainn commented
Okay, sounds good!

2024-04-29 15:10 UTC, tzumainn requested changes
Looks good! I think it could use one thing: in the README, could you add a quick explanation of how you'd use this sdk within a python script?

2024-04-29 17:02 UTC, DanNiESh commented
I've updated the README.md, let me know what you think!

2024-04-29 18:19 UTC, tzumainn requested changes
Thanks for adding the README! The code works well; there's just a few minor inaccuracies in the documentation that I've noted.

Could you also add a `connect` method, similar to https://github.com/openstack/openstacksdk/blob/master/openstack/__init__.py? What this allows one to do is have code like:

```
import openstack

conn = openstack.connect()
nodes = conn.baremetal.nodes(details=True)
```

And the openstacksdk will simply pull from your current environment.

2024-04-29 18:19 UTC, tzumainn commented on README.md
> +conn = connection.Connection(
I think this is actually ESIConnection

2024-04-29 18:19 UTC, tzumainn commented on README.md
> +conn = connection.Connection(config=config)
Here as well

2024-04-29 19:15 UTC, DanNiESh commented
> Thanks for adding the README! The code works well; there's just a few minor inaccuracies in the documentation that I've noted.
> 
> Could you also add a `connect` method, similar to https://github.com/openstack/openstacksdk/blob/master/openstack/__init__.py? What this allows one to do is have code like:
> 
> ```
> import openstack
> 
> conn = openstack.connect()
> nodes = conn.baremetal.nodes(details=True)
> ```
> 
> And the openstacksdk will simply pull from your current environment.

Done!

2024-04-30 14:10 UTC, tzumainn commented
This looks great - thanks!

2024-04-30 14:10 UTC, tzumainn approved these changes

2024-04-30 14:10 UTC, merged